### ISSUE TITLE
Maven artefacts aren't released.

### ISSUE THREAD

**Issue by Tzrlk** [zmeggyesi/migrator-maven-plugin#9]
Could you either release the maven artefacts to maven central (or equivalent), or rename your groupId to com.github.zmeggyesi so jitpack works properly?

**Comment by zmeggyesi** [comment]
Hi,

The idea was to have the user clone the repo, build, and run, originally. I did toy with the idea of releasing it, but never got around to it, and just wrote up the documentation with the appropriate commands accordingly.

I started the process, but it involves a 2-business-day wait from Sonatype to create the approved repo, so hang tight. I'll close the issue when the artifact is up on Central.

**Comment by zmeggyesi** [comment]
Everything seems to have gone through, though Maven Central is yet to index the artifact. I'll close this issue for now since the release has taken place, but please allow it a few hours to show up in a search.
